---

- name: add_packages | install epel release
  yum:
    name: epel-release
    state: present
  become: true

- name: add_packages | install common packages
  yum:
    name: "{{ common_packages }}"
    state: present
  become: true
    