---

- name: configure_network | debug_host_vars
  debug:
    msg:
      - "host var: {{ ipv4 }}"
      - "host var: {{ hostname }}"
  # - name: Add an Ethernet connection with static IP configuration
  #   nmcli:
  #   conn_name: my-eth1
  #   ifname: eth1
  #   type: ethernet
  #   ip4: 192.0.2.100/24
  #   gw4: 192.0.2.1
  #   state: present

  # - name: Add two IPv4   DNS server addresses
  #   nmcli:
  #     conn_name: my-eth1
  #     type: ethernet
  #     dns4:
  #     - 192.0.2.53
  #     - 198.51.100.53
  #     state: present