---

- name: configure_motd | hush root motd
  copy:
    path: /root/.hushlogin
    content: ""
    owner: root
    group: root
  become: yes

- name: configure_motd | drop motd.sh
  copy:
    src: motd.sh
    dest: /etc/profiles.d/
    mode: u=rwx,g=r,o=r
  become: true